# Generated by Django 3.2.2 on 2021-05-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_board", "0003_remove_article_up_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="amount_of_upvotes",
            field=models.IntegerField(default=0),
        ),
    ]
